# Generated by Django 3.1.7 on 2021-04-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_url',
        ),
    ]
