# Generated by Django 3.1.7 on 2021-04-01 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('q_likes', models.IntegerField(default=0)),
                ('asked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('q_dislikedby', models.ManyToManyField(related_name='disliked_by', to=settings.AUTH_USER_MODEL)),
                ('q_likedby', models.ManyToManyField(related_name='liked_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_url', models.URLField()),
                ('report_ques', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='Dashboard.questions')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answer_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer_likes', models.IntegerField(default=0)),
                ('answer_dislikedby', models.ManyToManyField(related_name='ansdisliked_by', to=settings.AUTH_USER_MODEL)),
                ('answer_l', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Dashboard.questions')),
                ('answer_likedby', models.ManyToManyField(related_name='ansliked_by', to=settings.AUTH_USER_MODEL)),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
